- hosts: rhel
  vars:
    current_version: 8.7
    target_version: 9.0
  tasks:
    - name: Prepare RHEL for upgrade
      include_role:
        name: prepare-rhel-upgrade
    - name: Changes for our demo env
      include_role:
        name: demo-prepare-rhel-upgrade

          #    - name: Answer pre-upgrade questions
          #      ansible.builtin.file:
          #        src: answerfile.userchoices
          #        dest: /var/log/leapp/answerfile.userchoices
          #        owner: root
          #        group: root
          #        mode: '0644'
          #      creates: /var/log/leapp/answerfile.userchoices
          #      become: true
          #
    - name: Preform RHEL upgrade
      include_role:
        name: rhel-upgrade
