---
# defaults file for prepare-rhel-upgrade

- name: Remove the /root/tmp_leapp_py3 directory if it is present 
  ansible.builtin.file:
    path: /root/tmp_leapp_py3/
    state: absent
  become: true
  
- name: Get current Subsription
  ansible.builtin.shell: subscription-manager list --installed
  register: subscription

  # TODO check if subscription is active
  # -------------------------------------------+
  #  Installed Product Status
  #+-------------------------------------------+
  #Product Name:   Red Hat Enterprise Linux for x86_64
  #Product ID:     479
  #Version:        8.7
  #Arch:           x86_64
  #Status:         Subscribed
  #Status Details:
  #Starts:         02/02/2023
  #Ends:           02/01/2024

- name: Add required repositories
  ansible.builtin.shell: subscription-manager repos --enable {{ repo }}
  loop: "{{ required_repos}}"

- name: Lock RHEL to latest minor release
  ansible.builtin.shell: subscription-manager release --set {{ current_version }} 

    #- name: Clear package version locks
    #ansible.builtin.shell: dnf versionlock clear

- name: Update RHEL to latest minor release
  ansible.builtin.shell: dnf update

- name: Reboot (this may take several minutes)
  ansible.builtin.reboot:
    reboot_timeout: 600
