---
# defaults file for demo-prepare-rhel-upgrade

- name: Install missing applications
  ansible.builtin.dnf:
    name: "{{ missing_apps }}"
    state: present

- name: Disable Root Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitRootLogin'
    line: PermitRootLogin no

- name: Firewalld Configuration AllowZoneDrifting Is Unsupported
  ansible.builtin.lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting='
    line: AllowZoneDrifting=no

- name: ensures /var/log/leapp/ dir exists
  file: 
    path: /var/log/leapp
    state: directory

- name: Answer pre-upgrade questions
  ansible.builtin.copy:
    src: answerfile.userchoices
    dest: /var/log/leapp/answerfile.userchoices
    owner: root
    group: root
    mode: '0644'
  become: true

